### ISSUE TITLE
Not working on 4.3 SGN

### ISSUE THREAD

**Issue by postaletter** [aviewdevs/aview#1]
I have hoping someone would put together an app like this but unfortunately it does not work. On start I get "An error has occured". I noticed there does not appear to be any signs of data transfer on the 3G or Wi-Fi icon in the notification bar.

Samsung Galaxy Nexus running stock 4.3, build JWR66R.

**Comment by aviewdevs** [comment]
Hi... This is odd, it works fine on both my 4.3 devices including a Nexus 4 on Build JWR66V.  The error message you're seeing is also what you see when you don't have a network connection.  Does this happen on both mobile data and wifi?  Does your device use an HTTP proxy?

**Comment by postaletter** [comment]
Thanks for reply. I just retried the app and it is working fine now. I had
tried with both Wi-Fi and 3G. The only thing I can think I that may have
fixed it is a reboot.

Sorry for the hassle. This app is going to be great for my kids and my
sanity, you are a legend.
